# DEBUG =  -fsanitize=address -g
FLAG = --std=c++98 -Wall -Werror -Wextra 
std: 
	@ echo "---------std--------" && c++  -D NS=std $(DEBUG) $(FLAG) main.cpp && ./a.out && rm -fr a.out a.out.*
ft: 
	@ echo "---------std--------" && c++  -D NS=std $(DEBUG) $(FLAG) main.cpp && ./a.out && rm -fr a.out a.out.*